version: '3.8'

services:
  api:
    image: brainhealth-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./uploads:/app/static
    restart: always    