"""empty message

Revision ID: 6a5b67e79259
Revises: 
Create Date: 2024-07-07 14:34:35.171679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5b67e79259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tumor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=16), nullable=False),
    sa.Column('perawatan', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=False),
    sa.Column('kata_sandi', sa.String(length=64), nullable=False),
    sa.Column('tipe', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nomor_telepon')
    )
    op.create_table('riwayat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap_pasien', sa.String(length=80), nullable=False),
    sa.Column('hasil', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('waktu', sa.Time(), nullable=False),
    sa.Column('gambar', sa.String(length=255), nullable=False),
    sa.Column('tumor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tumor_id'], ['tumor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riwayat')
    op.drop_table('user')
    op.drop_table('tumor')
    # ### end Alembic commands ###
