"""New migration

Revision ID: 8ea60491042a
Revises: 6a5b67e79259
Create Date: 2024-07-07 17:59:35.330151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea60491042a'
down_revision = '6a5b67e79259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('kata_sandi',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('kata_sandi',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
